services:
  - type: static
    name: hotel-booking-ui
    branch: main
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist/hotel-booking-service
    envVars:
      - key: NODE_ENV
        value: production